version: '3.4'

services:
  example1:
    image: ${DOCKER_REGISTRY}example1
    build:
      context: .
      dockerfile: src/Example1/Dockerfile
    depends_on:
      - sql.data
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
